version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.${ENVIRONMENT}
      args:
        NODE_VERSION: ${NODE_VERSION}
        PORT: ${PORT}
        APP_NAME: ${APP_NAME}
        COMPANY_NAME: ${COMPANY_NAME}
        ENVIRONMENT: ${ENVIRONMENT}
    environment:
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    ports:
      - 80:${PORT}
    volumes:
      - './src:/opt/${COMPANY_NAME}/${APP_NAME}/src'

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    ports:
      - 27017:27017
